drop database IF EXISTS Mvc;
CREATE DATABASE IF NOT EXISTS Mvc;

use Mvc;


CREATE TABLE Articles
(
  id_article INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title varchar(128) NOT NULL,
  content TEXT NOT NULL,
  dt_add timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
